version: '3.8'

services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "35432:5432"

  api:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    # command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle
      - /var/tmp
      - tmp-data:/app/tmp
      - sockets:/app/tmp/sockets
      - public-data:/app/public
      # - log-data:/app/log
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      # RAILS_ENV: production

    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - sockets:/app/tmp/sockets
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - api

volumes:
  postgres-data:
    driver: local
  sockets:
  public-data:
  tmp-data:
    driver: local
  log-data:
    driver: local
