version: '3.8'

services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
  api:
    build:
      context: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3001:3001
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local
